"""create missing tables

Revision ID: e328d4bb4d4e
Revises: add_text_library
Create Date: 2026-02-14 18:40:10.163885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e328d4bb4d4e'
down_revision: Union[str, None] = 'add_text_library'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Garantir que tipos ENUM existentes não causem DuplicateObject
    op.execute("""DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activitytype') THEN
        CREATE TYPE activitytype AS ENUM ('reading', 'writing', 'diagnostic');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activitydifficulty') THEN
        CREATE TYPE activitydifficulty AS ENUM ('easy', 'medium', 'hard');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activitystatus') THEN
        CREATE TYPE activitystatus AS ENUM ('pending', 'in_progress', 'completed');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'insighttype') THEN
        CREATE TYPE insighttype AS ENUM ('attention_needed', 'progress', 'suggestion');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'insightpriority') THEN
        CREATE TYPE insightpriority AS ENUM ('low', 'medium', 'high');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gender') THEN
        CREATE TYPE gender AS ENUM ('male', 'female', 'other');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'studentstatus') THEN
        CREATE TYPE studentstatus AS ENUM ('active', 'inactive');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'traildifficulty') THEN
        CREATE TYPE traildifficulty AS ENUM ('beginner', 'intermediate', 'advanced');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'diagnostictype') THEN
        CREATE TYPE diagnostictype AS ENUM ('initial', 'ongoing', 'final');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reporttype') THEN
        CREATE TYPE reporttype AS ENUM ('progress', 'diagnostic', 'full');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reportformat') THEN
        CREATE TYPE reportformat AS ENUM ('pdf', 'csv');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recordingstatus') THEN
        CREATE TYPE recordingstatus AS ENUM ('pending', 'processing', 'completed', 'failed');
    END IF;
END
$$;""")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', postgresql.ENUM('reading', 'writing', 'diagnostic', name='activitytype', create_type=False), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='activitydifficulty', create_type=False), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('words', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'completed', name='activitystatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_created_scheduled', 'activities', ['created_by', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_activities_created_by'), 'activities', ['created_by'], unique=False)
    op.create_index(op.f('ix_activities_scheduled_date'), 'activities', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', postgresql.ENUM('attention_needed', 'progress', 'suggestion', name='insighttype', create_type=False), nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', name='insightpriority', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_students', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=True),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='gender', create_type=False), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('special_needs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='studentstatus', create_type=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_students_name_gin', 'students', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_students_professional_id'), 'students', ['professional_id'], unique=False)
    op.create_index(op.f('ix_students_status'), 'students', ['status'], unique=False)
    op.create_table('trails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('difficulty', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='traildifficulty', create_type=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('age_range_min', sa.Integer(), nullable=True),
    sa.Column('age_range_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trails_created_by'), 'trails', ['created_by'], unique=False)
    op.create_index(op.f('ix_trails_difficulty'), 'trails', ['difficulty'], unique=False)
    op.create_table('diagnostics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('conducted_by', sa.UUID(), nullable=False),
    sa.Column('diagnostic_type', postgresql.ENUM('initial', 'ongoing', 'final', name='diagnostictype', create_type=False), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('reading_level', sa.String(length=50), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('ai_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_diagnostics_difficulties', 'diagnostics', ['difficulties'], unique=False, postgresql_using='gin')
    op.create_index('idx_diagnostics_student_created', 'diagnostics', ['student_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnostics_diagnostic_type'), 'diagnostics', ['diagnostic_type'], unique=False)
    op.create_index(op.f('ix_diagnostics_student_id'), 'diagnostics', ['student_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('report_type', postgresql.ENUM('progress', 'diagnostic', 'full', name='reporttype', create_type=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('format', postgresql.ENUM('pdf', 'csv', name='reportformat', create_type=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_progress', 'completed', name='activitystatus', create_type=False), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'activity_id', name='unique_student_activity')
    )
    op.create_table('trail_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trail_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('letters_focus', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('phonemes_focus', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='traildifficulty', create_type=False), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trail_stories_order', 'trail_stories', ['trail_id', 'order_position'], unique=False)
    op.create_index(op.f('ix_trail_stories_trail_id'), 'trail_stories', ['trail_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='recordingstatus', create_type=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['trail_stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recordings_student_date', 'recordings', ['student_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_recordings_recorded_at'), 'recordings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_recordings_status'), 'recordings', ['status'], unique=False)
    op.create_index(op.f('ix_recordings_story_id'), 'recordings', ['story_id'], unique=False)
    op.create_index(op.f('ix_recordings_student_id'), 'recordings', ['student_id'], unique=False)
    op.create_table('student_trail_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('trail_id', sa.UUID(), nullable=False),
    sa.Column('current_story_id', sa.UUID(), nullable=True),
    sa.Column('completed_stories', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_story_id'], ['trail_stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_id'], ['trails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'trail_id', name='unique_student_trail')
    )
    op.create_index(op.f('ix_student_trail_progress_student_id'), 'student_trail_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_trail_progress_trail_id'), 'student_trail_progress', ['trail_id'], unique=False)
    op.create_table('recording_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('prosody_score', sa.Float(), nullable=True),
    sa.Column('speed_wpm', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('errors_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pauses_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id')
    )
    op.create_index('idx_recording_analysis_errors', 'recording_analysis', ['errors_detected'], unique=False, postgresql_using='gin')
    op.alter_column('text_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('text_library', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('text_library', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_recording_analysis_errors', table_name='recording_analysis', postgresql_using='gin')
    op.drop_table('recording_analysis')
    op.drop_index(op.f('ix_student_trail_progress_trail_id'), table_name='student_trail_progress')
    op.drop_index(op.f('ix_student_trail_progress_student_id'), table_name='student_trail_progress')
    op.drop_table('student_trail_progress')
    op.drop_index(op.f('ix_recordings_student_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_story_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_status'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_recorded_at'), table_name='recordings')
    op.drop_index('idx_recordings_student_date', table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_trail_stories_trail_id'), table_name='trail_stories')
    op.drop_index('idx_trail_stories_order', table_name='trail_stories')
    op.drop_table('trail_stories')
    op.drop_table('student_activities')
    op.drop_table('reports')
    op.drop_index(op.f('ix_diagnostics_student_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_diagnostic_type'), table_name='diagnostics')
    op.drop_index('idx_diagnostics_student_created', table_name='diagnostics')
    op.drop_index('idx_diagnostics_difficulties', table_name='diagnostics', postgresql_using='gin')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_trails_difficulty'), table_name='trails')
    op.drop_index(op.f('ix_trails_created_by'), table_name='trails')
    op.drop_table('trails')
    op.drop_index(op.f('ix_students_status'), table_name='students')
    op.drop_index(op.f('ix_students_professional_id'), table_name='students')
    op.drop_index('idx_students_name_gin', table_name='students', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('students')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_scheduled_date'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_by'), table_name='activities')
    op.drop_index('idx_activities_created_scheduled', table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###

